function [fitresult, gof] = createFit(x, y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 2' fit:
%      X Input : x
%      Y Output: y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 13-Feb-2017 15:02:22


%% Fit: 'untitled fit 2'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.StartPoint = [0.0195115989323538 0.0317332591271696 0.186223130194823 0.00738397088694907 0.126933036508679 2.05740632427789];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 2' );
h = plot( fitresult, xData, yData );
legend( h, 'measurements', '0.0219 * sin(0.0383 * x - 0.1834) + 0.00832 * sin(0.1173 * x + 2.451)', 'Location', 'NorthEast' );
% Label axes
xlabel time
ylabel 'radial velocity'
title 'radial velocity vs time'
grid on


